### ISSUE TITLE
Nuova versione verificac19-sdk con supporto CRL

### ISSUE THREAD

**Issue by astagi** [Elius94/validate-c19-node-wrapper-executable#1]
Ciao @Elius94! ho rilasciato la nuova versione, ci sono alcune breaking change oltre che il supporto a MongoDB.

Note di rilascio: https://github.com/italia/verificac19-sdk/releases

Per qualsiasi supporto / richiesta di chiarimento fammi sapere!

**Comment by Elius94** [comment]
Grazie dell'avviso. Implementerò quanto prima! Buon anno. 😊

**Comment by astagi** [comment]
Top! Buon anno anche a te @Elius94 😁

**Comment by Elius94** [comment]
Rilasciata versione 1.1.0 che integra tutte le novità dell'SDK.

**Comment by astagi** [comment]
Grande @Elius94 !
